### ISSUE TITLE
Synchronisation von Emojis verkackt

### ISSUE THREAD

**Issue by JohannesStoehr** [onlyhats/jim#1]
:eat_zach: und :scroll_zach: sind nicht richtig synchronisiert.
Die Animation von der Essensanimation fängt ein Stück zu früh an.
Pls fix!

**Comment by RobinMarchart** [comment]
Upstream issue Raupinger/someStupidRepoSoJohannesCanOpenIssuesOnDiscordEmotes#1

**Comment by J-MR-T** [comment]
Das hab ich weder erstellt noch überhaupt selbst hinzugefügt, closed aus demselben Grund aus dem ein issue über die Farbe einer Pringels Dose im yay repository geclosed würde
